version: '3'
services:
  backend:
    build:
      context: .
    env_file: ./env
    volumes:
      - ./:/src
    ports:
      - 4000:4000
    depends_on:
      - mysql
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '3333:3333'
    environment:
      LOG_LEVEL: DEBUG
      PRISMA_CONFIG: |
        port: 3333
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~